### ISSUE TITLE
Listview vue inconsistencies

### ISSUE THREAD

**Issue by zbranzov** [NativeScript/nsplugins-internal#170]
- [x] Item selection - itemDeselect does not work  - related to https://github.com/telerik/nativescript-ui-feedback/issues/925
- [x] - Staggered layout - in iOS does not look well
- [x] - Scroll to item -  in iOS does not scroll to item 50 as in the other demos (vanilla/angular)
- [ ] Observable items - @create-item handler is called improperly https://screencast.com/t/aZ94d7Loh

**Comment by msaelices** [comment]
@zahhak

I've spent hours debugging the three first issues and all of them finish in some inner logic of the `TKListView`:

* The item de-selection issue was "fixed" [here](https://github.com/NativeScript/nativescript-ui-listview/commit/827bcde64e518d05477061675aa09ca37a1fb6bc), but the fix causes that the list styles are not refreshed and the gray background of the selected items are not shown (but they are actually selected). That's because of changing of an attribute of an object inside of an `ObservableArray` does not triggers a list "refresh" (not a total refresh). One of my tries to solve this was refreshing the list entirely, but it forgot the item selection status. The other approach was calling several inner methods which seems to notify the list was changed. 

* The second and third issue I guess share the same cause: there is an issue calculating the size of each item cell. I don't know why the same code in Angular is working because in theory there is no reason to miscalculate the size. Again, the miscalculation occurs inside a `TKListView` method which I'm not able to debug properly with the chrome inspector.

Is it possible to give me some tips about debugging or maybe a video conference to explain the issues properly?
 
CC/ @tgpetrov

**Comment by msaelices** [comment]
@zbranzov 

About the observables sample issue, it was an issue of the sample itself, and it was fixed [here](https://github.com/NativeScript/nativescript-ui-listview/commit/06dc242ab6654fe2ad10c374e70b4a1a27e1cec6). See these two screencast for [iOS](http://www.screencast.com/t/71Np7dx7AQ7I) and [Android](http://www.screencast.com/t/cLplWyUnFwtN). There is still a little "issue" about the first item added on iOS and the first three items added on Android, but again I did not consider it a Vue binding issue but a internal NS UI one, maybe because of internal optimizations.

CC/ @tgpetrov

**Comment by msaelices** [comment]
@zbranzov The first and the last issue was fixed in that PR: https://github.com/NativeScript/nativescript-ui-listview/pull/135

Thanks to @tgpetrov for your feedback and for fixing the de-selection problem.

**Comment by zbranzov** [comment]
@tgpetrov Unfortunately the fix of the staggered layout and scroll to item has broke some of the other examples https://screencast.com/t/yzrXc8MUqb

**Comment by zbranzov** [comment]
Last item left to be fixed is logged here https://github.com/telerik/nativescript-ui-feedback/issues/904
